[package]
name = "rosu_memory_lib"
version = "1.0.0"
edition = "2021"
description = "A library to read osu! memory"
license = "MIT"
repository = "https://github.com/Glubus/rosu-memory-lib"
authors = ["Glubus", "486c"]
keywords = ["osu", "memory", "game"]
categories = ["games", "memory-management"]


[lib]
name = "rosu_memory_lib"
path = "src/lib.rs"

[[bin]]
name = "rosu_memory_test"
path = "src/main.rs"

[dependencies]
rosu-mem = { git = "https://github.com/486c/rosu-mem.git", tag = "v2.0.0" }
eyre = "0.6.12"
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
serde_json = "1.0.140"
serde_repr = "0.1.20"
log = "0.4"
simplelog = "0.12"
rosu-pp = "3.1.0"
rosu-map = "0.2.1"
