[package]
name = "rosu-memory-c"
version = "0.1.0"
edition = "2021"

[lib]
name = "rosu_memory_c"
crate-type = ["cdylib", "staticlib"]

[dependencies]
rosu_memory_lib = { path = "../.." }
libc = "0.2"

[build-dependencies]
cbindgen = "0.29" 